# TensorFlow Basics

TensorFlow is an open-source deep learning framework developed by Google.

It provides a flexible and efficient ecosystem for building and training machine learning models.

TensorFlow allows you to define and execute computational graphs, where nodes represent operations and edges represent data flow.

It supports various neural network architectures, including feedforward networks, convolutional neural networks (CNNs), recurrent neural networks (RNNs), and more.

TensorFlow offers automatic differentiation, allowing you to compute gradients for optimizing models with gradient-based optimization algorithms.

It provides tools for distributed computing, model deployment, and productionizing machine learning applications.

## Basic Functions

`tf.constant(value)`: Creates a constant tensor with a specified value.

`tf.Variable(initial_value)`: Creates a mutable tensor variable.

`tf.placeholder(dtype)`: Creates a placeholder tensor for feeding data into the graph.

`tf.add(x, y)`: Adds two tensors element-wise.

`tf.matmul(a, b)`: Performs matrix multiplication of two tensors.

`tf.reduce_sum(input_tensor)`: Computes the sum of elements along specified axes.

`tf.reduce_mean(input_tensor)`: Computes the mean of elements along specified axes.

`tf.nn.relu(input_tensor)`: Applies the ReLU activation function element-wise.

`tf.nn.softmax(logits)`: Computes the softmax activation function element-wise.

`tf.argmax(input_tensor, axis)`: Returns the indices of the maximum values along a specified axis.

Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at tf.dtypes.DType.

If you're familiar with NumPy, tensors are (kind of) like np.arrays.

All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one. Here is a "scalar" or "rank-0" tensor . A scalar contains a single value, and no "axes".

## Importing TensorFlow

In [43]:
import tensorflow as tf

---

### Creating a scalar

In [44]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


---

### Creating a vector

A "vector" or "rank-1" tensor is like a list of values. A vector has one axis:

In [3]:
# let's make a float tensor

rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


---

### Creating a matrix

A "matrix" or "rank-2" tensor has two axes:

In [4]:
rank_2_tensor = tf.constant([[1,2],
                            [3,4],
                            [5,6]], dtype=tf.float16)

print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


---

### Creating a 3-axis tensor

Tensors may have more axes; here is a tensor with three axes:

Tensors may have more axes; here is a tensor with three axes:

In [6]:
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],
    [5,6,7,8,9]],
    [[10,11,12,13,14],
    [15,16,17,18,19]],
    [[20,21,22,23,24],
    [25,26,27,28,29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [10]:
print(rank_3_tensor[1][1][1])

tf.Tensor(16, shape=(), dtype=int32)


---

### Tensor operations

There are many ways you might visualize a tensor with more than two axes.

You can convert a tensor to a NumPy array either using np.array or the tensor.numpy method:

You can do basic math on tensors, including addition, element-wise multiplication, and matrix multiplication.

In [12]:
a = tf.constant([[1,2],
                [3,4]])
b = tf.constant([[1,1],
                [1,1]])

In [13]:
print(tf.add(a,b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [14]:
print(tf.multiply(a,b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [15]:
print(tf.matmul(a,b))

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


#### Element wise operations

In [18]:
# Performing element wise addition, multiplication and matrix multiplication
print(a+b, "\n")

print(a*b, "\n")

print(a@b, "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



---

What happens when we use tensors of a different shape?

In [27]:
ten1 = tf.constant([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

print(ten1.shape)

ten2 = tf.constant([[1,2,3],
                    [4,5,6]])

print(ten2.shape)

(3, 3)
(2, 3)


In [34]:
# Performing element wise addition, multiplication and matrix multiplication

try:
    print(tf.add(ten1, ten2), "\n")

    print(tf.multiply(ten1, ten2), "\n")

    print(tf.matmul(ten1, ten2), "\n")

except Exception as e:
    print(f"Exception occured: {e}")

Exception occured: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3,3] vs. [2,3] [Op:AddV2]


In [39]:
c = tf.constant([[4.0, 5.0], 
                [10.0, 1.0]])
print(c)

tf.Tensor(
[[ 4.  5.]
 [10.  1.]], shape=(2, 2), dtype=float32)


#### Finding Values

In [40]:
# Find the largest value
print(tf.reduce_max(c))

tf.Tensor(10.0, shape=(), dtype=float32)


In [41]:
# Find the index of the largest value
print(tf.math.argmax(c))

tf.Tensor([1 0], shape=(2,), dtype=int64)


In [42]:
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


`softmax()` is implemented as `tf.exp(logits)` / `tf.reduce_sum(tf.exp(logits), axis)`. It's important to understand each of these steps. Softmax is used in a lot of classifiers because it lets you interpret the outputs of the classifier as probabilities. For example, if the classifier has three outputs [0.1, 0.2, 0.7], you could interpret these as the probabilities that the input is class 0, class 1, and class 2 respectively. The probabilities add up to 1.0.

---

### Converting between data types

In [45]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [55]:
tf.reduce_max([1,8,3,5,23])

<tf.Tensor: shape=(), dtype=int32, numpy=23>

In [52]:
tf.reduce_max([[1,8,3,5,23],
                [2,4,3,4,51]])

<tf.Tensor: shape=(), dtype=int32, numpy=51>

---

### Shapes

About shapes

Tensors have shapes. Some vocabulary:

**Shape:** The length (number of elements) of each of the axes of a tensor.

**Rank:** Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.

**Axis or Dimension:** A particular dimension of a tensor.

**Size:** The total number of items in the tensor, the product of the shape vector's elements.

In [57]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)


In [59]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis first of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis first of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


---

### Indexing

#### Single-axis indexing

TensorFlow follows standard Python indexing rules, similar to indexing a list or a string in Python, and the basic rules for NumPy indexing.

Indexes start at <code>[0]</code>


Negative indices are countd backwards from the end. <br>
Colons '<code>:</code>' are used for slices

**Format:**<br>
`start:stop:step`

In [61]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


Indexing with a scalar removes the axis: 

In [67]:
print("First: ",rank_1_tensor[0].numpy())
print("Second: ",rank_1_tensor[1].numpy())
print("Last: ",rank_1_tensor[-1].numpy())

First:  0
Second:  1
Last:  34


Indexing with a colon '`:`' slice keeps the axis:

In [75]:
print("Everything:", rank_1_tensor[:].numpy())
print("Until the 4th element:", rank_1_tensor[:4].numpy())
print("From 4th to the end:", rank_1_tensor[4:].numpy())
print("After 2nd element, until 7th:", rank_1_tensor[2:7].numpy())
print("Every other item (skip an element):", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Until the 4th element: [0 1 1 2]
From 4th to the end: [ 3  5  8 13 21 34]
After 2nd element, until 7th: [1 2 3 5 8]
Every other item (skip an element): [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


#### Multi-axis indexing

Higher rank tensors are indexed by passing multiple indices.

The exact same rules as in the single-axis case apply to each axis independently.

In [76]:
print(rank_2_tensor.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [83]:
# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1][1].numpy())

4.0


In [84]:
# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



In [89]:
print(rank_3_tensor[:, :, 4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


### Manipulating Shapes

Reshaping a tensor is of great utility.

In [90]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


You can reshape a tensor into a new shape. The tf.reshape operation is fast and cheap as the underlying data does not need to be duplicated.

In [91]:
# You can reshape a tensor to a new shape.
# Note that you're passing in a list
reshaped = tf.reshape(x, [1, 3])
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


The data maintains its layout in memory and a new tensor is created, with the requested shape, pointing to the same data.

TensorFlow uses C-style "row-major" memory ordering, where incrementing the rightmost index corresponds to a single step in memory.

In [92]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


If you flatten a tensor you can see what order it is laid out in memory.

In [93]:
# A `-1` passed in the `shape` argument says "Whatever fits".
print(tf.reshape(rank_3_tensor, [-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


In [94]:
print(tf.reshape(rank_3_tensor, [3*2, 5]), "\n")
print(tf.reshape(rank_3_tensor, [3, -1]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)
